version: '3.8'

services:
  app:
    image: ghcr.io/swe-himelrana/tempmail:latest
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./tempmail.sample.yml
        target: /var/www/html/tempmail.yml
      - ./data:/var/www/html/data
    restart: unless-stopped
